- name: backend server
  hosts: backend
  become: yes
  vars: 

  tasks:
  - name: disable nodejs 
    ansible.builtin.command: dnf module disable nodejs -y
      
  - name: enable nodejs:20 -y
    ansible.builtin.command: dnf module enable nodejs:20 -y
      
  - name: install node js
    ansible.builtin.dnf: # Only works for Redhat Family
      name: nodejs
      state: latest

  - name: add user expense
    ansible.builtin.user:
      name: expense
      
  - name: create app directory 
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download the expense code
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip

  - name: unzip the file 
    ansible.builtin.unarchive:
      src: /tmp/backend.zip
      dest: /app
      remote_src: yes
      